# Resource group (create-or-reuse) and shared naming.
#
# create_resource_group = true  -> Terraform creates the group.
# create_resource_group = false -> an existing group of the same name is reused.
#
# This mirrors the "create if it doesn't already exist" behaviour you get with a
# resource-group-scoped Bicep deployment. Terraform tracks resources in state, so
# the toggle selects between a managed resource and a data lookup rather than
# performing an in-place upsert.

resource "azurerm_resource_group" "this" {
  count    = var.create_resource_group ? 1 : 0
  name     = var.resource_group_name
  location = var.location
  tags     = var.tags
}

data "azurerm_resource_group" "existing" {
  count = var.create_resource_group ? 0 : 1
  name  = var.resource_group_name
}

# Current Azure CLI principal - granted storage data-plane access below.
data "azurerm_client_config" "current" {}

locals {
  resource_group_name     = var.create_resource_group ? azurerm_resource_group.this[0].name : data.azurerm_resource_group.existing[0].name
  resource_group_location = var.create_resource_group ? azurerm_resource_group.this[0].location : data.azurerm_resource_group.existing[0].location
  resource_group_id       = var.create_resource_group ? azurerm_resource_group.this[0].id : data.azurerm_resource_group.existing[0].id

  # Resource names come straight from variables - no autogenerated suffixes.
  storage_account_name  = var.storage_account_name
  workspace_name        = var.workspace_name
  access_connector_name = var.access_connector_name
}
